permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: Jake Jiang
  email: 2015chinamac@gmail.com
  link: http://jake2015.org
#  weibo: http://weibo.com/yansu0711
  github: http://github.com/JakeJiang

# 站点信息
title: Jake Jiang的博客 
description: Jake Jiang的博客
url: http://jake2015.org
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://image.weiosx.com/Jake.jpg
favicon: http://image.weiosx.com/Jake.icns

# google analytics 设置
# ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: JakeJiang

# 主题设置，自动激活某个标签
# active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
